name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@master
      with:
        timeZone: UTC+8
        format: 'YYYYMMDDHHmmss'
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        TS: "${{ steps.time.outputs.time }}"
      with:
        push: true
        platforms: |
          linux/arm64/v8
        tags: |
          xiaoql/pytorch-modelzoo:latest
          xiaoql/mindspore_2_0_0:cann6.3rc1-py-mindformers-euler-${{ steps.time.outputs.time }}
